New back
go-park-mail-ru/2022_2_GoTo_team pull request #3
Opened 2022-11-09 06:34 UTC by VarenytsiaMykhailo

2022-11-09 08:27 UTC, spiridonovaalexis requested changes
Тесты не хватает

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/categoryComponent/usecase/categoryUsecase.go
> +	wrappingErrorMessage := "error while getting info for category"
оборачивать ошибку лучше снаружи
и можно в константу такое сообщение вынести

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/domain/interfaces/userComponentInterfaces/userComponentInterfaces.go
> +type UserUsecaseInterface interface {
мне кажется, лучше разделить хранение интерфейсов по слоям
И можно хранить интерфейсы рядом с реализацией

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/domain/customErrors/categoryComponentErrors/usecaseToDeliveryErrors/usecaseToDeliveryErrors.go
> +type RepositoryError struct {
Зачем такая ошибка для каждой модели есть?

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/articleComponent/delivery/articleController.go
> +			Login:    article.CoAuthor.Login,
Зачем тут нужен логин?

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/domain/models/user.go
> +	RegistrationDate   string
почему не time.Date?

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/utils/logger/logger.go
> +	if len(logFilePath) != 0 {
```
if len(logFilePath) == 0 {
    return nil, errors.New("incorrect logFilePath: is empty")
}

...
```

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/utils/validators/validators.go
> +	emailRFC5322RegExp = `^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$` // RFC 5322. https://sta
`regexp.Compile()` можно тут использовать

А в `EmailIsValidByRegExp` матчить уже к скомпилированной регулярке

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/utils/validators/validators.go
> +	return err == nil && match
ошибка может возникнуть по другой причине, все равно нужно ее проверять и логировать

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/utils/validators/validators.go
> +		if (en && !unicode.Is(unicode.Latin, sep)) || (!en && unicode.Is(unicode.Latin, sep)) {
`unicode.Is(unicode.Latin, sep)` в переменную можно

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/sessionComponent/repository/sessionCustomRepository.go
> +	sessions map[string]string // K: sessionId, V: email
А почему не использовали key-value бд для хранилища сессий?

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/sessionComponent/repository/sessionCustomRepository.go
> +func generateRandomRunesString(length int) string {
это в utils надо вынести

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/sessionComponent/repository/sessionCustomRepository.go
> +	ss.logger.LogrusLoggerWithContext(ctx).Info("For the email ", email, " created the session.")
в логгере нет префикса в email?

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/sessionComponent/repository/sessionCustomRepository.go
> +	ss.logger.LogrusLoggerWithContext(ctx).Infof("The session %s has been removed", session)
Это наверное все-таки дебаг

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/userComponent/repository/userPostgreSQLRepository.go
> +SELECT U.user_id,
Запросы можно вынести в константы

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/userComponent/usecase/userUsecase.go
> +		return &usecaseToDeliveryErrors.EmailIsNotValidError{Err: errors.New("email is not valid")}
Может лучше в функцию обернуть создание ошибок?

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/serverRestApi.go
> +	sessionDeliveryLogger, err := logger.NewLogger("sessionComponent", domain.LAYER_DELIVERY_STRING_FOR_LOGGER, config.LogLevel, config.LogFilePath)
Хватило бы и по логгеру на каждый слой, но раз вы уже сразу на компоненты разбили

2022-11-09 08:27 UTC, spiridonovaalexis commented on internal/serverRestAPI/middleware/accessLogMiddleware.go
> +package middleware
лучше middleware более очевидно выделить как слой

2022-11-10 05:21 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/categoryComponent/usecase/categoryUsecase.go
> +	wrappingErrorMessage := "error while getting info for category"
Здесь представлена стратегия оборачивания, одобренная и предложенная Григорием Мироновым - информация об ошибки уровня бизнес-логики.
В константу вынести не получится - будет очень некрасиво т..к. в файле может быть несколько публичных апи-функций уровня usecase и для каждой требуется свое текстовое описание ошибки. Если все такие строки вынести в константы, то кроме каши придется еще думать об уникальном названии переменной для каждой из строки. Поэтому я решил ввести спецификацию по обработке ошибок в проекте для уровня usecase: внутри каждого публичного api-метода usecase, в самом начале заводить строку wrappingErrorMessage с описанием бизнес-ошибки данного публичного метода. Все ошибки, пробрасываемые публичным методом выше в деливере должны быть обернуты с использованием wrappingErrorMessage

2022-11-10 05:23 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/domain/interfaces/userComponentInterfaces/userComponentInterfaces.go
> +type UserUsecaseInterface interface {
> мне кажется, лучше разделить хранение интерфейсов по слоям И можно хранить интерфейсы рядом с реализацией

Судя по примерам лекций интерфейсы должны храниться в директории domain. В ней подразумевается определение структур и интерфейсов, которые могут использоваться в нескольких слоях usecase/delivery/repository одновременно

2022-11-10 05:30 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/domain/customErrors/categoryComponentErrors/usecaseToDeliveryErrors/usecaseToDeliveryErrors.go
> +type RepositoryError struct {
> Зачем такая ошибка для каждой модели есть?

В результате обсуждения вопроса по стратегии оборачивания ошибок с Григорием Ммироновом, он запретил возвращать ошибки СУБД из слоя repository. Но из repository обычно прилетают два типа ошибок: кастомная ошибка СУБД (RepositoryError) и ошибка, если что-то в базе не найдено (например, EmailDontExistsError). Такого типа ошибки пробрасываются от репозитория в юзкейс. Подразумевается, что RepositoryError - это ошибка работы приложения (СУБД упало) или недочетов программиста (SQL запрос написан с косяками), ассоциирующаяся с кодом возврата 500. Мы должны ее пробросить в деливере и указать ее тип RepositoryError, чтобы слой деливери мог отличить эту ошибку от других типов ошибок и вернуть нужный код (в данном случае - 500). 
P.S. Я стараюсь писать код так, чтобы ошибки RepositoryError никогда не возникали. Но как бы хорошо не был написан код, вероятность возникновения этой ошибки присутствует всегда и мы должны обрабатывать эту информацию всегда и честно пробрасывать эту ошибку до деливери

2022-11-10 05:36 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/articleComponent/delivery/articleController.go
> +			Login:    article.CoAuthor.Login,
> Зачем тут нужен логин?

Это вопрос к Владимиру (я подстраиваюсь под его АПИ, которое он придумывает, а я подстраиваюсь и предоставляю реализацию). На сколько я понял, ему требуется в этой структуре уникальное значение автора из базы, чтобы делать ссылки с возможным переходом в профиль автора. Логин - уникально идентифицирует авторов. 
P.S. Возможно в будущем перейдем на логику с введением дополнительных айдишников в базе: external_id с типом UUID, предназначенного для использования вне рамок базы (по советам препода по СУБД). Тогда вместо логинов и других естественных ключей будем пользоваться "внешними айдишниками". Но препод по СУБД сказал что для нашего уровня нормально пользоваться естественными ключами и на счет введения внешних айдишников для учебного  проекта не стоит заморачиваться (но за доп баллы по ГО я не против переписать логику с использованием внешних айдишников в виде UUID)

2022-11-10 06:53 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/domain/models/user.go
> +	RegistrationDate   string
> почему не time.Date?

К сожалению, в пакете time нет типа Date. Есть тип time.Time, но он подразумевает хранение даты + полное время + друга мета-информация. Нам же нужно, чтобы в JSON-ах хранилась только дата в формате 01-01-2022. Самый простой способ реализовать это - в структурах на гоу использовать тип string, а преобразование полной даты типа TIMESTAMP из базы в нужный формат производить средствами SQL при извлечении. 
Если подскажете более элегантное решение как добиться хранения даты в нужном формате используя соответствующий тип данных на Go - буду рад (но пока все попахивает подключением сторонних библиотек)

2022-11-10 07:00 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/utils/logger/logger.go
> +	if len(logFilePath) != 0 {
> ```
> if len(logFilePath) == 0 {
>     return nil, errors.New("incorrect logFilePath: is empty")
> }
> 
> ...
> ```

отрефакторил

2022-11-10 07:24 UTC, spiridonovaalexis commented on internal/serverRestAPI/domain/customErrors/categoryComponentErrors/usecaseToDeliveryErrors/usecaseToDeliveryErrors.go
> +type RepositoryError struct {
Это ок, но зачем одинаковую ошибку создавать несколько раз, если по смыслу она одна и та же везде?

2022-11-10 07:33 UTC, spiridonovaalexis commented on internal/serverRestAPI/domain/models/user.go
> +	RegistrationDate   string
Да, я перепутала time.Date c time.Time
Ну в принципе, если вам так ок и нигде в коде это не проблема

2022-11-10 07:34 UTC, spiridonovaalexis commented on internal/serverRestAPI/articleComponent/delivery/articleController.go
> +			Login:    article.CoAuthor.Login,
Поняла, он у вас вместо id-ков

2022-11-10 07:34 UTC, spiridonovaalexis commented on internal/serverRestAPI/articleComponent/delivery/articleController.go
> +			Login:    article.CoAuthor.Login,
А другим пользователям показывается username?

2022-11-10 07:39 UTC, spiridonovaalexis commented on internal/serverRestAPI/categoryComponent/usecase/categoryUsecase.go
> +	wrappingErrorMessage := "error while getting info for category"
У тебя вот тут создается новая кастомная ошибка, и ты ее тут же оборачиваешь
`return nil, errorsUtils.WrapError(wrappingErrorMessage, &usecaseToDeliveryErrors.CategoryDontExistsError{Err: err})`
И далее то же самое делаешь для другой ошибки, а если их 10 будет

И пояснительная ошибка у тебя совпадает с названием функции, с таким сообщением логично оборачивать именно снаружи

2022-11-10 08:25 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/categoryComponent/usecase/categoryUsecase.go
> +	wrappingErrorMessage := "error while getting info for category"
> 

Ну тут варианта два:
1. Оставляем все как есть
2. Удаляем везде заворачивание ошибок в ошибку с сообщением из переменной wrappingErrorMessage  (описание бизнес-процесса в котором случилась ошибка), поскольку в слое деливери эта информация не используется и, по сути, не нужна. Поэтому оборачивание снаружи вообще не требуется. Но Григорий говорил, что правильней сделать так, чтобы из юскейса прилетала ошибка, в которой содержится информация о не выполнении бизнес-процесса, например "error while adding new user" для публичного метода AddUser из usecase

2022-11-10 08:34 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/domain/customErrors/categoryComponentErrors/usecaseToDeliveryErrors/usecaseToDeliveryErrors.go
> +type RepositoryError struct {
> 

В проекте я придерживаюсь принципа - для каждого компонента свой набор ошибок, определенные в определенном пакете, соответствующему компоненту. Кроме того, наборы ошибок для компонентов разделяются на два вида: ошибки, предназначенные для проброса из репозитория в юзкейс, и ошибки, предназначенные для проброса из юзкейс в деливери.
Если не придерживаться этого принципа, то в проекте будут ошибки предназначенные для конкретного компонента и ошибки, которые используются в некоторых компонентах. Это чревато проблемами (изменили функционал какой-то ошибки, а он неявно отображается в других компонентах, в которых используется эта ошибка).
Но в принципе, от описанного принципа можно немного отойти и сделать RepositoryError общей для всех компонентов, поскольку эта ошибка используется во всех компонентах (пока в проекте это только одна такая "общая" по смыслу ошибка и ее действительно можно переиспользовать). Тогда придется ввести пакет allComponentErrors и разместить ее там. Выбор за вами)

2022-11-10 08:38 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/articleComponent/delivery/articleController.go
> +			Login:    article.CoAuthor.Login,
> 

Да. Причем в username может, фактически, тоже лежать "логин". Владимир придумал супер бизнес-логику: если username у пользователя в базе NULL, то я должен в поле username подкладывать логин, при извлечении с помощью SQL запроса) тогда у пользователя вместо юзернейма будет отображаться его логин

2022-11-10 08:39 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/utils/validators/validators.go
> +	emailRFC5322RegExp = `^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$` // RFC 5322. https://sta
> 

Пофиксил. Изменения отобразятся при следующем пуше

2022-11-10 08:41 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/utils/validators/validators.go
> +	return err == nil && match
> ошибка может возникнуть по другой причине, все равно нужно ее проверять и логировать

Пофиксил. Изменения отобразятся при следующем пуше. Теперь ошибки никакой не будет в принципе:
![image](https://user-images.githubusercontent.com/52725148/201042235-840f2840-e74c-49e7-afa0-212058ee38b3.png)
Регулярка компилируется во время сборки проекта с помощью метода regexp.MustCompile

2022-11-10 08:44 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/sessionComponent/repository/sessionCustomRepository.go
> +	sessions map[string]string // K: sessionId, V: email
> А почему не использовали key-value бд для хранилища сессий?

В планах есть использовать редис. Я оставлял эту задачу Александру (типа я занимаюсь общей базой, проектированием, постгресом и слоями репозитори, а он только слоем репозитори для сессии и редисом), но он пропал) постараюсь завезти чуть позже.

2022-11-10 08:50 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/utils/validators/validators.go
> +		if (en && !unicode.Is(unicode.Latin, sep)) || (!en && unicode.Is(unicode.Latin, sep)) {
> 

Вообще удалил этот метод, он больше не используется. Изменения отобразятся при следующем пуше.

2022-11-10 08:55 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/sessionComponent/repository/sessionCustomRepository.go
> +func generateRandomRunesString(length int) string {
> это в utils надо вынести

Пофиксил. Изменения отобразятся при следующем пуше.

2022-11-10 09:02 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/sessionComponent/repository/sessionCustomRepository.go
> +	ss.logger.LogrusLoggerWithContext(ctx).Infof("The session %s has been removed", session)
> 
Полезно оставить в инфо, чтобы у админа боевого сервера была возможность следить, какие пользователи разлогинились, а какие залогинились. Причем можно будет в будущем добавить информацию об устройстве и других "активных" сессиях пользователя. Но это все требует глубокого обдумывания логики

2022-11-10 09:14 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/userComponent/repository/userPostgreSQLRepository.go
> +SELECT U.user_id,
> 

Я против и на то у меня есть несколько причин:
1. Сейчас ведется активная разработка и запросы постоянно меняются. Пока выгодно, чтобы они объявлялись там, где используются
2. Если в файле будет 20 функций запросов, и 20 констант с запросами сверху и потребуется что-то изменить в запросе, добавить новое поле, то придется: в верху файла внести изменение в строку запроса, затем найти функцию и добавить нужные аргументы в плейсхолдеры. Иными словами, вынесение строк в константу оправдано, если для изменения логики программы достаточно разок изменить константную строку и больше править ничего не нужно. В случае с SQL запросами все равно потребуется лезть в фунцию и менять еще и там, а так же для оптимизации, чтобы компилятор мог "инлайнить константную строку в нескольких местах ее использования". Но у нас каждая строка будет использоваться только в одном месте, поэтому в этой оптимизации нет смысла.
3. Ни в лекциях ни в других источниках информации никогда не видел, чтобы строки с запросами делами константными и выносили в другое место

2022-11-10 09:22 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/userComponent/usecase/userUsecase.go
> +		return &usecaseToDeliveryErrors.EmailIsNotValidError{Err: errors.New("email is not valid")}
> Может лучше в функцию обернуть создание ошибок?

Типа такого?
`return useCaseToDeliveryErrors.MakeEmailIsNotValidError(errors.New("email is not valid"))
`?
Если да, то в таком случае для каждой кастомной ошибки придется написать свою функцию. В принципе, вызов такой функции выглядит приятней, чем ручное создание и заполнение структуры. Но принято ли так создавать ошибки в GoLang с помощью функций? Я таких примеров не видел... но если Григорий или кто-то из других преподавателей поддержит, то я переделаю во всех местах логику создания кастомных ошибок через функции (переделывать придется во многих местах, поэтому хотелось бы точно определиться и взвесить все "за" и "против")

2022-11-10 09:51 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/serverRestApi.go
> +	sessionDeliveryLogger, err := logger.NewLogger("sessionComponent", domain.LAYER_DELIVERY_STRING_FOR_LOGGER, config.LogLevel, config.LogFilePath)
> Хватило бы и по логгеру на каждый слой, но раз вы уже сразу на компоненты разбили

У меня тут для каждого компонента и для каждого его слоя компонента свой логгер. Но то, что вы описали - тут создается, скорее, обертка над логгером, которая использует "контекст" - дополнительную метаинформацию для сообщений логов (какой именно компонент, какой именно слой, какой уровень логгирования использовать конкретно для этого слоя конкретного компонента. Можно еще кучу дополнительной информации задать).
Почему обертка? Физически в программе на все компоненты и на все слои существуют лишь один логгер (глобальная переменная globalLogrusLogger в файле config.go). Под капотом все созданные обертки используют глобальный логгер

2022-11-10 12:06 UTC, VarenytsiaMykhailo commented on internal/serverRestAPI/sessionComponent/repository/sessionCustomRepository.go
> +	ss.logger.LogrusLoggerWithContext(ctx).Info("For the email ", email, " created the session.")
> в логгере нет префикса в email?

Реализовал вывод емаила в логгере (выводится, если пользователь зашел с нормальной кукой)

2022-11-10 12:54 UTC, spiridonovaalexis commented on internal/serverRestAPI/userComponent/usecase/userUsecase.go
> +		return &usecaseToDeliveryErrors.EmailIsNotValidError{Err: errors.New("email is not valid")}
Если у тебя такая ошибка
`errors.New("email is not valid")`
то можно прям тут возвращать

А если ты возвращаешь ссылку на новую структуру,  то красивее обернуть это функцию, независимо от того, ошибка это или нет

2022-11-10 14:49 UTC, merged